version: "3.8"
  
services:
  sqldb:
    image: mariadb:10.5.18
    ports:
      - 53301:3306
    volumes: # 배포한 mariadb_tmplt를 본인 PC로 복사하고, 해당 위치 경로로 수정하여 사용
      - /Users/phoenix/Eagle/2025_FastAPIs/mariadb_tmplt/conf.d:/etc/mysql/conf.d
      - /Users/phoenix/Eagle/2025_FastAPIs/mariadb_tmplt/data:/var/lib/mysql
      - /Users/phoenix/Eagle/2025_FastAPIs/mariadb_tmplt/initdb.d:/docker-entrypoint-initdb.d
      - /Users/phoenix/Eagle/2025_FastAPIs/mariadb_tmplt/bak:/home/bak
    env_file: env
    environment:
      TZ: Asia/Seoul
    command: "mysqld --innodb-buffer-pool-size=2G --innodb_buffer_pool_instances=2"
    networks:
      - backend
    restart: always

networks:
  backend:

# docker compose -p <프로젝트명> -f <파일명> up -d, mariadb.yaml -> 기본 파일인 docker-compose.yml 대신 사용
# docker compose -p maria_db -f maria_db.yaml up -d

# client는 다음 링크에서 Mysql Workbench 다운로드하여 사용
# https://dev.mysql.com/downloads/workbench/

# DBMS 접속 후, 다음 스키마 정보 생성하여 사용.
# > CREATE SCHEMA 'demo' DEFAULT CHARACTER SET utf8mb4 ;
# > CREATE USER 'manager'@'%' IDENTIFIED BY 'SqlDba-1’ ; 컨테이너로 실행한 경우는 USER는 이미 생성되어 있으므로 생략합니다.
# > GRANT ALL PRIVILEGES ON demo.* TO 'manager'@'%' IDENTIFIED BY 'SqlDba-1’;
# > FLUSH PRIVILEGES;
